spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/xtu_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

logging:
  level:
    com.xtu.system: debug
